remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
name: "Dmytro Tymoshenko"

title: Borrelia Burgdorferi Project
description: The project is funded by Genome Atlantic to study the diversity of Lyme disease-causing spirochaete bacteria (genus/species = Borrelia burgdorferi) in Nova Scotian ticks and in patient biopsies.
